### ISSUE TITLE
Usage from Safe Rust

### ISSUE THREAD

**Issue by LoganDark** [Vurv78/luau-rs#5]
I noticed that you snagged a couple names on crates.io as well, so I came to take a look at what you were working on.

I'm opening this issue to help track the addition of an API that can be used from Safe Rust. My crate has an [example](https://github.com/LoganDark/luau-rs/blob/c56fddc748d888c9a8b1d3b02cf5633e5279482c/examples/basic_run.rs) of what using Luau from Safe Rust might look like; it compiles and runs but that's about all the functionality that's implemented right now:

```rs
use std::ffi::CStr;

use luau::vm::{Luau, StackValue, Value};

fn main() {
	let vm = Luau::new().expect("failed to create Luau VM");
	let compiled = Luau::compile("return ...")
		.expect("failed to compile function");

	let chunkname = CStr::from_bytes_with_nul(b"=basic_run.luau\0").expect("die");
	let main_thread = vm.main_thread();
	let function = main_thread.load_compiled(compiled, chunkname)
		.expect("failed to load function");

	println!("{:?}", function.call_sync([
		Value::new_string(&main_thread, "hello world").unwrap(),
		Value::new_string(&main_thread, "I like trains").unwrap(),
		Value::new_string(&main_thread, "how about a table?").unwrap(),
		Value::new_table(&main_thread, 0, 0).unwrap(),
		Value::new_string(&main_thread, "I like trains").unwrap()
	]));

	// assert stack usage is balanced
	assert_eq!(unsafe { StackValue::stack(main_thread.as_ptr()) }, Vec::new());
}
```

If you can manage to get autocxx to generate bindings to the high-level C++ magic like analysis and AST, your crate could pretty quickly speed ahead of mine in the compilation/analysis department, since I'm focusing on VM right now. Different versions of Luau can't be mixed in the same application (or else linking errors result), [so I've just added a feature to my crate that allows users to disable compilation and linking to Luau](https://github.com/LoganDark/luau-rs/commit/47b486a1c51ba09f1068237b6af9a3070ae09f68) so that people have the choice to use your crate as the compiler if they so choose.

Good luck and may the best crate win! :)

**Comment by vurvdev** [comment]
Right now the goal is to be a crate similar to https://github.com/lilyball/rust-lua rather than something like rlua or hlua which are deeply abstracted for safety, which your library seems to be aiming for.

This is to keep the crate pretty maintainable and paired with Luau.
Also yes, the ast should be fine, need to make sure with some unit tests though..

Once all bindings are made either through work on Autocxx or manual bindings I may expose a safe(r) api, but we'll see 👍

**Comment by LoganDark** [comment]
> deeply abstracted for safety

Not just for safety, but also for ease of use. The Lua stack can be elegant, but only sometimes, but there are no variable names and it can be unclear what's going on, so allowing values to be stored in Rust variables is a huge step towards maintainable C functions. Additionally, I plan on supporting async functions (as yieldable C functions), since Rust does all the hard work of encoding the function into a state machine (which is what yieldable C functions require).

Probably the most difficult part of this is satisfying the compiler's alias analysis and avoiding undefined behavior. I'm pretty sure I still have some UB in there right now.

Of course, since my implementation is currently being actively worked on, there's a bit less reason to start your own - unless of course there's something valuable you can bring to the table! :P (Competition is good)

**Comment by vurvdev** [comment]
Done. Of course not completely, but it's setup, ( this is 0.1.1 i'm talking about, so )
